version: '3.7'
services:
  
  oauth-server:
    image: oauth2-server:1.0 
    ports: 
      - 8888:8888 
    restart: always
    environment:
      - DOCKER=1

  web-server:
    image: ng-web-server:1.0
    ports: 
      - 8080:8080 
    restart: always
    environment:
      - DOCKER=1
